package cn.appia.im.core.theme

import androidx.compose.ui.graphics.Color

/**
 * RN `src/theme/colors.ts` 的逐字段转录（字段名保持 RN 命名）。
 *
 * - light/dark/black 中的 `...mentions` 对象展开转录为同名字段。
 * - `SWITCH_TRACK_COLOR*` 中的 `rgba(...)` 保持 RN 原式，转为 Compose 浮点构造，不做手工换算。
 */
class Palette(
    val primary: Color,
    val backgroundColor: Color,
    val focusedBackground: Color,
    val chatComponentBackground: Color,
    val auxiliaryBackground: Color,
    val bannerBackground: Color,
    val titleText: Color,
    val bodyText: Color,
    val backdropColor: Color,
    val dangerColor: Color,
    val successColor: Color,
    val borderColor: Color,
    val controlText: Color,
    val auxiliaryText: Color,
    val infoText: Color,
    val tintColor: Color,
    val tintActive: Color,
    val tintDisabled: Color,
    val auxiliaryTintColor: Color,
    val actionTintColor: Color,
    val separatorColor: Color,
    val navbarBackground: Color,
    val headerBorder: Color,
    val headerBackground: Color,
    val headerSecondaryBackground: Color,
    val headerTintColor: Color,
    val headerTitleColor: Color,
    val headerSecondaryText: Color,
    val toastBackground: Color,
    val videoBackground: Color,
    val favoriteBackground: Color,
    val hideBackground: Color,
    val messageboxBackground: Color,
    val searchboxBackground: Color,
    val buttonBackground: Color,
    val buttonText: Color,
    val passcodeBackground: Color,
    val passcodeButtonActive: Color,
    val editAndUploadButtonAvatar: Color,
    val passcodeLockIcon: Color,
    val passcodePrimary: Color,
    val passcodeSecondary: Color,
    val passcodeDotEmpty: Color,
    val passcodeDotFull: Color,
    val previewBackground: Color,
    val previewTintColor: Color,
    val backdropOpacity: Float,
    val attachmentLoadingOpacity: Float,
    val collapsibleQuoteBorder: Color,
    val collapsibleChevron: Color,
    val cancelButton: Color,
    val conferenceCallBorder: Color,
    val conferenceCallBackground: Color,
    val conferenceCallOngoingPhoneBackground: Color,
    val conferenceCallIncomingPhoneBackground: Color,
    val conferenceCallEndedPhoneBackground: Color,
    val conferenceCallOngoingPhoneIcon: Color,
    val conferenceCallIncomingPhoneIcon: Color,
    val conferenceCallEndedPhoneIcon: Color,
    val conferenceCallPlusUsersButton: Color,
    val conferenceCallPlusUsersText: Color,
    val conferenceCallCallBackButton: Color,
    val conferenceCallCallBackText: Color,
    val conferenceCallDisabledIcon: Color,
    val conferenceCallEnabledIcon: Color,
    val conferenceCallEnabledIconBackground: Color,
    val conferenceCallPhotoBackground: Color,
    val textInputSecondaryBackground: Color,
    val unreadColor: Color,
    val tunreadColor: Color,
    val mentionMeColor: Color,
    val mentionGroupColor: Color,
    val mentionOtherColor: Color,
)

/** RN `STATUS_COLORS`. */
class StatusColors(
    val online: Color,
    val busy: Color,
    val away: Color,
    val offline: Color,
    val loading: Color,
    val disabled: Color,
)

/** RN `SWITCH_TRACK_COLOR*`，键名为 `true`/`false`. */
class SwitchTrackColors(
    val `true`: Color,
    val `false`: Color,
)

object AppiaColors {

    val light = Palette(
        primary = Color(0xFF2878FF),
        backgroundColor = Color(0xFFFFFFFF),
        focusedBackground = Color(0xFFFFFFFF),
        chatComponentBackground = Color(0xFFF3F4F5),
        auxiliaryBackground = Color(0xFFEFEFF4),
        bannerBackground = Color(0xFFF1F2F4),
        titleText = Color(0xFF0D0E12),
        bodyText = Color(0xFF2F343D),
        backdropColor = Color(0xFF000000),
        dangerColor = Color(0xFFF5455C),
        successColor = Color(0xFF2DE0A5),
        borderColor = Color(0xFFE1E5E8),
        controlText = Color(0xFF54585E),
        auxiliaryText = Color(0xFF9CA2A8),
        infoText = Color(0xFF6D6D72),
        tintColor = Color(0xFF1D74F5),
        tintActive = Color(0xFF549DF9),
        tintDisabled = Color(0xFF88B4F5),
        auxiliaryTintColor = Color(0xFF6C727A),
        actionTintColor = Color(0xFF1D74F5),
        separatorColor = Color(0xFFCBCBCC),
        navbarBackground = Color(0xFFFFFFFF),
        headerBorder = Color(0xFFB2B2B2),
        headerBackground = Color(0xFFEEEFF1),
        headerSecondaryBackground = Color(0xFFFFFFFF),
        headerTintColor = Color(0xFF6C727A),
        headerTitleColor = Color(0xFF0C0D0F),
        headerSecondaryText = Color(0xFF1D74F5),
        toastBackground = Color(0xFF0C0D0F),
        videoBackground = Color(0xFF1F2329),
        favoriteBackground = Color(0xFFFFBB00),
        hideBackground = Color(0xFF54585E),
        messageboxBackground = Color(0xFFFFFFFF),
        searchboxBackground = Color(0xFFE6E6E7),
        buttonBackground = Color(0xFF414852),
        buttonText = Color(0xFFFFFFFF),
        passcodeBackground = Color(0xFFEEEFF1),
        passcodeButtonActive = Color(0xFFE4E7EA),
        editAndUploadButtonAvatar = Color(0xFFE4E7EA),
        passcodeLockIcon = Color(0xFF6C727A),
        passcodePrimary = Color(0xFF2F343D),
        passcodeSecondary = Color(0xFF6C727A),
        passcodeDotEmpty = Color(0xFFCBCED1),
        passcodeDotFull = Color(0xFF6C727A),
        previewBackground = Color(0xFF1F2329),
        previewTintColor = Color(0xFFF9F9F9),
        backdropOpacity = 0.3f,
        attachmentLoadingOpacity = 0.7f,
        collapsibleQuoteBorder = Color(0xFFCBCED1),
        collapsibleChevron = Color(0xFF6C727A),
        cancelButton = Color(0xFFE4E7EA),
        conferenceCallBorder = Color(0xFFF2F3F5),
        conferenceCallBackground = Color(0xFFF7F8FA),
        conferenceCallOngoingPhoneBackground = Color(0xFFC0F6E4),
        conferenceCallIncomingPhoneBackground = Color(0xFFD1EBFE),
        conferenceCallEndedPhoneBackground = Color(0xFFE4E7EA),
        conferenceCallOngoingPhoneIcon = Color(0xFF158D65),
        conferenceCallIncomingPhoneIcon = Color(0xFF095AD2),
        conferenceCallEndedPhoneIcon = Color(0xFF6C727A),
        conferenceCallPlusUsersButton = Color(0xFFE4E7EA),
        conferenceCallPlusUsersText = Color(0xFF6C727A),
        conferenceCallCallBackButton = Color(0xFFEEEFF1),
        conferenceCallCallBackText = Color(0xFF1F2329),
        conferenceCallDisabledIcon = Color(0xFF6C727A),
        conferenceCallEnabledIcon = Color(0xFFFFFFFF),
        conferenceCallEnabledIconBackground = Color(0xFF156FF5),
        conferenceCallPhotoBackground = Color(0xFFE4E7EA),
        textInputSecondaryBackground = Color(0xFFE4E7EA),
        unreadColor = Color(0xFFD91F1B),
        tunreadColor = Color(0xFF1D74F5),
        mentionMeColor = Color(0xFFF5455C),
        mentionGroupColor = Color(0xFFF38C39),
        mentionOtherColor = Color(0xFFF3BE08),
    )

    val dark = Palette(
        primary = Color(0xFF2878FF),
        backgroundColor = Color(0xFF030B1B),
        focusedBackground = Color(0xFF0B182C),
        chatComponentBackground = Color(0xFF192132),
        auxiliaryBackground = Color(0xFF07101E),
        bannerBackground = Color(0xFF0E1F38),
        titleText = Color(0xFFF9F9F9),
        bodyText = Color(0xFFCBCED1),
        backdropColor = Color(0xFF000000),
        dangerColor = Color(0xFFF5455C),
        successColor = Color(0xFF2DE0A5),
        borderColor = Color(0xFF0F213D),
        controlText = Color(0xFFDADDE6),
        auxiliaryText = Color(0xFF9297A2),
        infoText = Color(0xFF6D6D72),
        tintColor = Color(0xFF1D74F5),
        tintActive = Color(0xFF549DF9),
        tintDisabled = Color(0xFF88B4F5),
        auxiliaryTintColor = Color(0xFFF9F9F9),
        actionTintColor = Color(0xFF1D74F5),
        separatorColor = Color(0xFF2B2B2D),
        navbarBackground = Color(0xFF0B182C),
        headerBorder = Color(0xFF2F3A4B),
        headerBackground = Color(0xFF0B182C),
        headerSecondaryBackground = Color(0xFF0B182C),
        headerTintColor = Color(0xFFF9F9F9),
        headerTitleColor = Color(0xFFF9F9F9),
        headerSecondaryText = Color(0xFF9297A2),
        toastBackground = Color(0xFF0C0D0F),
        videoBackground = Color(0xFF1F2329),
        favoriteBackground = Color(0xFFFFBB00),
        hideBackground = Color(0xFF54585E),
        messageboxBackground = Color(0xFF0B182C),
        searchboxBackground = Color(0xFF192D4D),
        buttonBackground = Color(0xFF414852),
        buttonText = Color(0xFFFFFFFF),
        passcodeBackground = Color(0xFF030C1B),
        passcodeButtonActive = Color(0xFF0B182C),
        editAndUploadButtonAvatar = Color(0xFF0B182C),
        passcodeLockIcon = Color(0xFF6C727A),
        passcodePrimary = Color(0xFFFFFFFF),
        passcodeSecondary = Color(0xFFCBCED1),
        passcodeDotEmpty = Color(0xFFCBCED1),
        passcodeDotFull = Color(0xFF6C727A),
        previewBackground = Color(0xFF030B1B),
        previewTintColor = Color(0xFFF9F9F9),
        backdropOpacity = 0.9f,
        attachmentLoadingOpacity = 0.3f,
        collapsibleQuoteBorder = Color(0xFFCBCED1),
        collapsibleChevron = Color(0xFF6C727A),
        cancelButton = Color(0xFFE4E7EA),
        conferenceCallBorder = Color(0xFF1F2329),
        conferenceCallBackground = Color(0xFF1F2329),
        conferenceCallOngoingPhoneBackground = Color(0xFF106D4F),
        conferenceCallIncomingPhoneBackground = Color(0xFFD1EBFE),
        conferenceCallEndedPhoneBackground = Color(0xFF6C727A),
        conferenceCallOngoingPhoneIcon = Color(0xFFF7F8FA),
        conferenceCallIncomingPhoneIcon = Color(0xFF095AD2),
        conferenceCallEndedPhoneIcon = Color(0xFFF7F8FA),
        conferenceCallPlusUsersButton = Color(0xFF2F343D),
        conferenceCallPlusUsersText = Color(0xFF9EA2A8),
        conferenceCallCallBackButton = Color(0xFFE4E7EA),
        conferenceCallCallBackText = Color(0xFFFFFFFF),
        conferenceCallDisabledIcon = Color(0xFF6C727A),
        conferenceCallEnabledIcon = Color(0xFFFFFFFF),
        conferenceCallEnabledIconBackground = Color(0xFF156FF5),
        conferenceCallPhotoBackground = Color(0xFFE4E7EA),
        textInputSecondaryBackground = Color(0xFF030B1B),
        unreadColor = Color(0xFFD91F1B),
        tunreadColor = Color(0xFF1D74F5),
        mentionMeColor = Color(0xFFF5455C),
        mentionGroupColor = Color(0xFFF38C39),
        mentionOtherColor = Color(0xFFF3BE08),
    )

    val black = Palette(
        primary = Color(0xFF2878FF),
        backgroundColor = Color(0xFF000000),
        focusedBackground = Color(0xFF0D0D0D),
        chatComponentBackground = Color(0xFF16181A),
        auxiliaryBackground = Color(0xFF080808),
        bannerBackground = Color(0xFF1F2329),
        titleText = Color(0xFFF9F9F9),
        bodyText = Color(0xFFCBCED1),
        backdropColor = Color(0xFF000000),
        dangerColor = Color(0xFFF5455C),
        successColor = Color(0xFF2DE0A5),
        borderColor = Color(0xFF1F2329),
        controlText = Color(0xFFDADDE6),
        auxiliaryText = Color(0xFFB2B8C6),
        infoText = Color(0xFF6D6D72),
        tintColor = Color(0xFF1E9BFE),
        tintActive = Color(0xFF76B7FC),
        tintDisabled = Color(0xFF88B4F5),
        auxiliaryTintColor = Color(0xFFF9F9F9),
        actionTintColor = Color(0xFF1E9BFE),
        separatorColor = Color(0xFF272728),
        navbarBackground = Color(0xFF0D0D0D),
        headerBorder = Color(0xFF323232),
        headerBackground = Color(0xFF0D0D0D),
        headerSecondaryBackground = Color(0xFF0D0D0D),
        headerTintColor = Color(0xFFF9F9F9),
        headerTitleColor = Color(0xFFF9F9F9),
        headerSecondaryText = Color(0xFFB2B8C6),
        toastBackground = Color(0xFF0C0D0F),
        videoBackground = Color(0xFF1F2329),
        favoriteBackground = Color(0xFFFFBB00),
        hideBackground = Color(0xFF54585E),
        messageboxBackground = Color(0xFF0D0D0D),
        searchboxBackground = Color(0xFF1F1F1F),
        buttonBackground = Color(0xFF414852),
        buttonText = Color(0xFFFFFFFF),
        passcodeBackground = Color(0xFF000000),
        passcodeButtonActive = Color(0xFF0E0D0D),
        editAndUploadButtonAvatar = Color(0xFF0E0D0D),
        passcodeLockIcon = Color(0xFF6C727A),
        passcodePrimary = Color(0xFFFFFFFF),
        passcodeSecondary = Color(0xFFCBCED1),
        passcodeDotEmpty = Color(0xFFCBCED1),
        passcodeDotFull = Color(0xFF6C727A),
        previewBackground = Color(0xFF000000),
        previewTintColor = Color(0xFFF9F9F9),
        backdropOpacity = 0.9f,
        attachmentLoadingOpacity = 0.3f,
        collapsibleQuoteBorder = Color(0xFFCBCED1),
        collapsibleChevron = Color(0xFF6C727A),
        cancelButton = Color(0xFFE4E7EA),
        conferenceCallBorder = Color(0xFF1F2329),
        conferenceCallBackground = Color(0xFF1F2329),
        conferenceCallOngoingPhoneBackground = Color(0xFF106D4F),
        conferenceCallIncomingPhoneBackground = Color(0xFFD1EBFE),
        conferenceCallEndedPhoneBackground = Color(0xFF6C727A),
        conferenceCallOngoingPhoneIcon = Color(0xFFF7F8FA),
        conferenceCallIncomingPhoneIcon = Color(0xFF095AD2),
        conferenceCallEndedPhoneIcon = Color(0xFFF7F8FA),
        conferenceCallPlusUsersButton = Color(0xFF2F343D),
        conferenceCallPlusUsersText = Color(0xFF9EA2A8),
        conferenceCallCallBackButton = Color(0xFFE4E7EA),
        conferenceCallCallBackText = Color(0xFFFFFFFF),
        conferenceCallDisabledIcon = Color(0xFF6C727A),
        conferenceCallEnabledIcon = Color(0xFFFFFFFF),
        conferenceCallEnabledIconBackground = Color(0xFF156FF5),
        conferenceCallPhotoBackground = Color(0xFFE4E7EA),
        textInputSecondaryBackground = Color(0xFF000000),
        unreadColor = Color(0xFFD91F1B),
        tunreadColor = Color(0xFF1D74F5),
        mentionMeColor = Color(0xFFF5455C),
        mentionGroupColor = Color(0xFFF38C39),
        mentionOtherColor = Color(0xFFF3BE08),
    )

    val status = StatusColors(
        online = Color(0xFF2DE0A5),
        busy = Color(0xFFF5455C),
        away = Color(0xFFFFD21F),
        offline = Color(0xFFCBCED1),
        loading = Color(0xFF9EA2A8),
        disabled = Color(0xFFF38C39),
    )

    val switchTrack = SwitchTrackColors(
        `true` = Color(0xFF2878FF),
        `false` = Color(red = 0f, green = 0f, blue = 0f, alpha = 0.2f), // rgba(0, 0, 0, 0.2)
    )

    val switchTrackDisabled = SwitchTrackColors(
        `true` = Color(red = 40f / 255f, green = 120f / 255f, blue = 255f / 255f, alpha = 0.6f), // rgba(40, 120, 255, 0.6)
        `false` = Color(red = 0f, green = 0f, blue = 0f, alpha = 0.2f), // rgba(0, 0, 0, 0.2)
    )
}
