package cn.appia.im.feature.chatlist

import cn.appia.im.core.database.entity.ChatEntity

/**
 * chatlist 测试共用的 ChatEntity 行工厂：未列出的列走实体默认值。
 * 分类/排序只用这些字段，其余列（alert/tunread/…）留默认即可。
 */
internal fun chatRow(
    _id: String,
    t: String = "c",
    f: Boolean = false,
    like: Boolean? = null,
    ts: Double = 0.0,
    lm: Double? = null,
    subscription_updated_at: Double? = null,
    tSearch: Double? = null,
    unread: Double = 0.0,
    hide_unread_status: Boolean? = null,
    draft_message: String? = null,
    draft_message_plain: String? = null,
    todoCount: Double? = null,
    highTodoCount: Double? = null,
    uids: String? = null,
    usernames: String? = null,
    name: String = "n",
    fname: String = "",
    dname: String? = null,
    open: Boolean = true,
    archived: Boolean = false,
    bot: Boolean? = null,
): ChatEntity = ChatEntity(
    _id = _id,
    f = f,
    t = t,
    ts = ts,
    ls = 0.0,
    name = name,
    fname = fname,
    rid = _id,
    open = open,
    alert = false,
    unread = unread,
    user_mentions = 0.0,
    group_mentions = 0.0,
    room_updated_at = 0.0,
    ro = false,
    archived = archived,
    auto_translate_language = "en",
    team_id = "",
    like = like,
    lm = lm,
    subscription_updated_at = subscription_updated_at,
    tSearch = tSearch,
    hide_unread_status = hide_unread_status,
    draft_message = draft_message,
    draft_message_plain = draft_message_plain,
    todoCount = todoCount,
    highTodoCount = highTodoCount,
    uids = uids,
    usernames = usernames,
    dname = dname,
    bot = bot,
)
