package cn.appia.im.core.database.entity

import androidx.room.Entity
import androidx.room.Index
import androidx.room.PrimaryKey

/**
 * 对照 appiaMobile `src/database/schema.ts`（WatermelonDB v6）`subscriptions` 表逐列转录（83 列）。
 * string→String、number→Double、boolean→Boolean；isOptional→可空；JSON 列存原文 String。
 */
@Entity(tableName = "subscriptions",
    indices = [
        Index(value = ["t"]),
        Index(value = ["name"]),
        Index(value = ["rid"]),
        Index(value = ["team_id"]),
    ],
)
data class SubscriptionEntity(
    @PrimaryKey
    val _id: String,
    val f: Boolean,
    val t: String,
    val ts: Double,
    val ls: Double,
    val name: String,
    val fname: String,
    val rid: String,
    val open: Boolean,
    val alert: Boolean,
    val roles: String? = null,
    val unread: Double,
    val user_mentions: Double,
    val group_mentions: Double,
    val tunread: String? = null,
    val tunread_user: String? = null,
    val tunread_group: String? = null,
    val lm: Double? = null,
    val room_updated_at: Double,
    val subscription_updated_at: Double? = null,
    val ro: Boolean,
    val last_open: Double? = null,
    val last_message: String? = null,
    val description: String? = null,
    val announcement: String? = null,
    val announcements: String? = null,
    val room_value_proposition: String? = null,
    val banner_closed: Boolean? = null,
    val topic: String? = null,
    val blocked: Boolean? = null,
    val blocker: Boolean? = null,
    val react_when_read_only: Boolean? = null,
    val archived: Boolean,
    val join_code_required: Boolean? = null,
    val muted: String? = null,
    val ignored: String? = null,
    val broadcast: Boolean? = null,
    val prid: String? = null,
    val draft_message: String? = null,
    val draft_message_plain: String? = null,
    val draft_reply_msg_id: String? = null,
    val last_thread_sync: Double? = null,
    val jitsi_timeout: Double? = null,
    val auto_translate: Boolean? = null,
    val auto_translate_language: String,
    val hide_unread_status: Boolean? = null,
    val disable_notifications: Boolean? = null,
    val sys_mes: String? = null,
    val uids: String? = null,
    val usernames: String? = null,
    val visitor: String? = null,
    val department_id: String? = null,
    val served_by: String? = null,
    val livechat_data: String? = null,
    val tags: String? = null,
    val e2e_key: String? = null,
    val e2e_suggested_key: String? = null,
    val encrypted: Boolean? = null,
    val e2e_key_id: String? = null,
    val avatar_etag: String? = null,
    val team_id: String,
    val team_main: Boolean? = null,
    val on_hold: Boolean? = null,
    val source: String? = null,
    val hide_mention_status: Boolean? = null,
    val users_count: Double? = null,
    val federated: Boolean? = null,
    val rt: String? = null,
    val todoCount: Double? = null,
    val dname: String? = null,
    val onCallStatus: Boolean? = null,
    val callMsg: String? = null,
    val bot: Boolean? = null,
    val welcomeMsg: String? = null,
    val memberName: String? = null,
    val memberNumber: Double? = null,
    val showAppiaTag: Double? = null,
    val isRoomToDo: Boolean? = null,
    val highTodoCount: Double? = null,
    val defaultTodoCount: Double? = null,
    val like: Boolean? = null,
    val tSearch: Double? = null,
    val appiaUsage: String? = null,
)
